config/routes.rb
Rails.application.routes.draw do

  get 'pusher/auth'

  post 'pusher/auth', to: 'pusher#auth'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :users
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  root to: 'pages#home'

  get 'intro', to: 'pages#intro'

  resources :users, only: [:show, :edit, :update] do
    # delete 'deactivate', on: :member
    member do
      get :personality
      get :questionnaire
      post :calculate_insight
    end

    resources :questions, only: [:show] do
      resources :answers, only: [:new, :create]
    end
  end

  resources :rooms, only: [:create, :show]
  resources :questions, only: [:index, :new, :create, :edit, :update] #pundit
  resources :matches, only: [:index]
  resources :answers, only: [:edit, :update, :destroy]
  resources :ratings, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to questions_path
    else
      render :edit
    end
  end



private


def question_params
  params.require(:question).permit(:content)
end



end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/edit.html.erb
<h1>Update question n<%= @question.id %></h1>

<%= simple_form_for @question do |f| %>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>

app/views/questions/index.html.erb
<div class="container">
<h1>All Questions</h1>


<%= link_to "Create", new_question_path, class: "btn btn-primary"%>

      <% @questions.each do |question| %>

        <h2><%= question .id%> . <%= question.content %></h2>

      <br>
      <%= link_to "Edit", edit_question_path(question), class: "btn btn-primary"%>
      <% end %>


</div>

app/views/questions/new.html.erb
<h1>New question</h1>


<%= simple_form_for @question do |f| %>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>