config/routes.rb
Rails.application.routes.draw do

  get 'pusher/auth'

  post 'pusher/auth', to: 'pusher#auth'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :users
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  root to: 'pages#home'

  get 'intro', to: 'pages#intro'

  resources :users, only: [:show, :edit, :update] do
    # delete 'deactivate', on: :member
    member do
      get :personality
      get :questionnaire
      post :calculate_insight
    end

    resources :questions, only: [:show] do
      resources :answers, only: [:new, :create]
    end
  end

  resources :rooms, only: [:create, :show]
  resources :questions, only: [:index, :new, :create, :edit, :update] #pundit
  resources :matches, only: [:index]
  resources :answers, only: [:edit, :update, :destroy]
  resources :ratings, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  require 'typhoeus'
  require 'json'
  has_many :sent_ratings, :foreign_key => :sender_id, class_name: 'Rating'
  has_many :ratings, :foreign_key => :recipient_id
  has_many :answers, dependent: :destroy
  has_many :questions, through: :answers
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #:confirmable

  validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 18, less_than: 120 }

  before_save :default_values
  def default_values
    self.avatar ||= '/avatar/001.png'
  end


  def unanswered_questions
    Question.where.not(id: self.questions.map(&:id)).sample
  end

  def answered_minimum_questions?
    answers.sum_of_content >= 100 ? true : false
  end

  def percentage
    if (( answers.sum_of_content / 100.0 ) * 100) <= 100
      (( answers.sum_of_content / 100.0 ) * 100).to_s
    else
      100
    end
  end

  def init_answers
    File.open("tmp/answer_user_#{self.id}.txt","w") do |line|

      questions.each do |question|
        line.puts question.content
        question.answers.each do |answer|
          line.puts answer.content
        end
      end
    end
  end

  def get_insight

    init_answers

    response = Typhoeus::Request.post("https://gateway.watsonplatform.net/personality-insights/api/v3/profile?version=2016-10-20",
                  :username => "46c8f693-d5a1-48bd-9151-9ae46165421e",
                  :password => "FQcfP0dTMPPY",
                  :headers => {'Content-Type' => 'text/plain;charset=utf-8'},
                  :body => {'data-binary' => File.open("tmp/answer_user_#{self.id}.txt")})
    self.insight = JSON.parse(response.response_body)
    self.save!
  end

  def print_insight
    insight_hash = {}
    unless self.insight.nil?
      unless self.insight["personality"].nil?
        (0..4).to_a.each do |i|
          (0..5).to_a.each do |j|
            insight_hash[self.insight["personality"][i]["children"][j]["name"]] = (self.insight["personality"][i]["children"][j]["percentile"] * 100).round
          end
        end
      end
    end
    insight_hash
  end

  def add_scores
    matches_hash = {}

    User.where.not(id: self.id).each do |user|
      matches_hash[user.id] = calculate_score(user)
    end

    matches_hash
  end

  def calculate_score(user)
    origin = self
    target = user
    score = 0.0

    origin_traits = {}

   unless target.insight.nil?
    unless target.insight["personality"].nil?
      (0..4).to_a.each do |i|
        (0..5).to_a.each do |j|
          origin_traits[origin.insight["personality"][i]["children"][j]["name"]] = origin.insight["personality"][i]["children"][j]["percentile"]
        end
      end
    end
  end

    target_traits ={}


  unless target.insight.nil?
    unless target.insight["personality"].nil?
    (0..4).to_a.each do |i|
      (0..5).to_a.each do |j|
        target_traits[target.insight["personality"][i]["children"][j]["name"]] = target.insight["personality"][i]["children"][j]["percentile"]
      end
    end

    score += 1 - (target_traits["Adventurousness"] - origin_traits["Adventurousness"]).abs
    score += 1 - (target_traits["Artistic interests"] - origin_traits["Artistic interests"]).abs
    score += 1 - (target_traits["Emotionality"] - origin_traits["Emotionality"]).abs
    score += 1 - (target_traits["Imagination"] - origin_traits["Imagination"]).abs
    score += 1 - (target_traits["Intellect"] - origin_traits["Intellect"]).abs
    score += 1 - (target_traits["Authority-challenging"] - origin_traits["Authority-challenging"]).abs
    score += 1 - (target_traits["Achievement striving"] - origin_traits["Achievement striving"]).abs
    score += 1 - (target_traits["Cautiousness"] - origin_traits["Cautiousness"]).abs
    score += 1 - (target_traits["Dutifulness"] - origin_traits["Dutifulness"]).abs
    score += 1 - (target_traits["Orderliness"] - origin_traits["Orderliness"]).abs
    score += 1 - (target_traits["Self-discipline"] - origin_traits["Self-discipline"]).abs
    score += 1 - (target_traits["Self-efficacy"] - origin_traits["Self-efficacy"]).abs
    score += 1 - (target_traits["Activity level"] - origin_traits["Activity level"]).abs
    score += 1 - (target_traits["Assertiveness"] - origin_traits["Assertiveness"]).abs
    score += 1 - (target_traits["Cheerfulness"] - origin_traits["Cheerfulness"]).abs
    score += 1 - (target_traits["Excitement-seeking"] - origin_traits["Excitement-seeking"]).abs
    score += 1 - (target_traits["Outgoing"] - origin_traits["Outgoing"]).abs
    score += 1 - (target_traits["Gregariousness"] - origin_traits["Gregariousness"]).abs
    score += 1 - (target_traits["Altruism"] - origin_traits["Altruism"]).abs
    score += 1 - (target_traits["Cooperation"] - origin_traits["Cooperation"]).abs
    score += 1 - (target_traits["Uncompromising"] - origin_traits["Uncompromising"]).abs
    score += 1 - (target_traits["Sympathy"] - origin_traits["Sympathy"]).abs
    score += 1 - (target_traits["Trust"] - origin_traits["Trust"]).abs
    score += 1 - (target_traits["Fiery"] - origin_traits["Fiery"]).abs
    score += 1 - (target_traits["Prone to worry"] - origin_traits["Prone to worry"]).abs
    score += 1 - (target_traits["Melancholy"] - origin_traits["Melancholy"]).abs
    score += 1 - (target_traits["Immoderation"] - origin_traits["Immoderation"]).abs
    score += 1 - (target_traits["Self-consciousness"] - origin_traits["Self-consciousness"]).abs
    score += 1 - (target_traits["Susceptible to stress"] - origin_traits["Susceptible to stress"]).abs

    score = (score/29)*100
    score = score.round

    score

    end
  end
    score
  end


  # instead of deleting, indicate the user requested a delete & timestamp it
  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end

  # ensure user account is active
  def active_for_authentication?
    super && !deleted_at
  end

  # provide a custom message for a deleted account
  def inactive_message
    !deleted_at ? super : :deleted_account
  end

  def overall_rating
    scores = []
    self.ratings.each do |rating|
      scores << ((rating.helpfulness.to_f + rating.response_time.to_f + rating.empathy.to_f) / 3.0)
     end
     (scores.inject(&:+) / scores.length.to_f)
  end

#  def online?
 #   if ((DateTime.current - self.last_sign_in_at.to_datetime).to_i * 24) < 5
  #    true
    #else
   #   false
    #end
  #end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # DELETE /resource
  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_flashing_format?
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :redirect_to_custom_path, only: :show

  def show
    if params[:seen_intro].present?
      User.find(current_user.id).update(seen_intro: true)
    end

    @answer = Answer.new
    # @user = current_user
    @user = User.find(params[:id])
    # @question = Question.find(params[:question_id])
    @question = current_user.unanswered_questions

    # @matches_hash = current_user.add_scores
    # @matches_hash = @matches_hash.sort_by { |id, score| score }.reverse
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    authorize @user, :update?
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def deactivate
    @user = User.find(params[:id])
    authorize @user
    @user.deactivate
    if @user.save
      redirect_to destroy_user_session_path
    else
      render :show
    end
  end

  def calculate_insight
    @user = User.find(params[:id])
    @user.get_insight
    redirect_to user_path(@user, tab: 'personality')
  end

  private

  def user_params
    params.require(:user).permit(:avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def tab_hidden(tab, params)
    if tab == 'questionnaire' && !params.present?
      ""
    elsif tab != params
      "hidden"
    end
  end


  def tab_active(tab, params)
    if tab == params
      "active"
    elsif tab == 'questionnaire' && !params.present?
        "active"
    end

  end
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/personality.html.erb
<div class="profile-header-wrapper">
  <div class="container profile-header-container text-center">
    <div class="profile-header-infos">
      <%= image_tag "#{@user.avatar}", class: "profile-picture"%>
      <h1><%= @user.username %></h1>
      <h2>member since <%= @user.created_at.strftime("%Y") %></h2>
    </div>
      <%= render partial: "shared/menu", locals: { active: 'personality' } %>
  </div>
</div>


<div class="container text-center">
      <div class="tab-content" id="personality">
        <% if @user == current_user %>
          <% @user.print_insight %>
          <%= link_to "Calculate Your Personality Insight", calculate_insight_user_path(@user.id), method: :post, :class => "btn btn-primary" %>
        <% end %>
        <br>
        <br>
        <div class="row">
          <div class="col-xs-6">
            <h1 class="text-blue">Values</h1>
            <br>

            <h5 class="align-center text-blue">Emotionality</h5>
            <progress  class="align-center" max="100" value="<%= @user.print_insight["Emotionality"] %>"></progress>



            <h5 class="align-center text-blue">Excitement-seeking</h5>
            <progress  class="align-center" max="100" value="<%= @user.print_insight["Excitement-seeking"] %>"></progress>



            <h5 class="align-center text-blue">Adventurousness</h5>
            <progress  class="align-center" max="100" value="<%= @user.print_insight["Adventurousness"] %>"></progress>

            <h5 class="align-center text-blue">Artistic interests</h5>
            <progress  class="align-center" max="100" value="<%= @user.print_insight["Artistic interests"] %>"></progress>

            <h5 class="align-center text-blue">Achievement striving</h5>
            <progress  class="align-center" max="100" value="<%= @user.print_insight["Achievement striving"] %>"></progress>
          </div>
          <div class="col-xs-6">
            <h1 class="text-blue">Personality</h1>
            <br>

            <h5 class="align-center text-blue">Openness</h5>
            <progress  class="align-center" max="100" value="<%= @user.print_insight["Openness"] %>"></progress>

            <h5 class="align-center text-blue">Sympathy</h5>
            <progress  class="align-center" max="100" value="<%= @user.print_insight["Sympathy"] %>"></progress>

            <h5 class="align-center text-blue">Agreeableness</h5>
            <progress  class="align-center" max="100" value="<%= @user.print_insight["Agreeableness"] %>"></progress>


            <h5 class="align-center text-blue">Melancholy</h5>
            <progress  class="align-center" max="100" value="<%= @user.print_insight["Melancholy"] %>"></progress>





            <h5 class="align-center text-blue">Imagination</h5>
            <progress  class="align-center" max="100" value="<%= @user.print_insight["Imagination"] %>"></progress>
          </div>
          </div>
        </div>




</div>

app/views/users/questionnaire.html.erb
<div class="profile-header-wrapper">
  <div class="container profile-header-container text-center">
    <div class="profile-header-infos">
      <%= image_tag "#{@user.avatar}", class: "profile-picture"%>
      <h1><%= @user.username %></h1>
      <h2>member since <%= @user.created_at.strftime("%Y") %></h2>
    </div>
      <%= render partial: "shared/menu", locals: { active: 'questionnaire' } %>
  </div>
</div>

<div class="container text-center">
<div class="tab-content" id="questionnaire">
  <%= render 'answers/listing', user: @user %>
</div>

</div>

app/views/users/show.html.erb
<% content_for :title, "Profile #{@user.username}" %>
<div class="profile-header-wrapper">
  <div class="container profile-header-container text-center">
    <div class="profile-header-infos">
      <%= image_tag "#{@user.avatar}", class: "profile-picture"%>
      <h1><%= @user.username %></h1>
      <h2>member since <%= @user.created_at.strftime("%Y") %></h2>
    </div>
    <div class="tabs">
      <a class="tab <%= tab_active('questionnaire',params[:tab])%>" data-target="#questionnaire">
       <h3><%= image_tag "002-questions.svg", class: "tab-icon"%>Questionnaire</h3>
      </a>
      <a class="tab <%= tab_active('personality',params[:tab])%>" data-target="#personality">
        <h3><%= image_tag "001-user.svg", class: "tab-icon"%>Personality</h3>
      </a>
      <% if @user != current_user %>
        <%= link_to rooms_path(recipient: @user.id), method: :post, class: "tab" do %>
          <h3><%= image_tag "003-chat.svg", class: "tab-icon" %>Converse now!</h3>
        <% end %>
      <% else %>
        <%= link_to matches_path, class: "tab" do %>
          <h3><%= image_tag "003-chat.svg", class: "tab-icon" %> Matches </h3>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="container text-center">
  <div class="tab-content <%= tab_hidden('personality', params[:tab])%>" id="personality">
    <br>
    <br>
    <div class="row">
      <div class="col-xs-8">
        <canvas id="chartweb1" width="250" height="250"></canvas>
      </div>

      <!-- </div> -->
      <div class="col-xs-4">
        <h3 class="align-center text-blue">Values</h3>
        <canvas id="chartPole" width="250" height="250"></canvas>
      </div>

        <% if @user == current_user %>
          <% @user.print_insight %>
          <%= link_to "Calculate Your Personality Insight", calculate_insight_user_path(@user.id), method: :post, :class => "btn btn-primary" , :id => "insightButton"%>
        <% end %>

    </div>
  </div>


      <div class="tab-content <%= tab_hidden('questionnaire', params[:tab])%>" id="questionnaire">
        <%= render 'answers/listing', user: @user %>
      </div>
</div>



    <% if @user == current_user %>
        <%# link_to "Deactivate account", user_registration_path, method: :delete %>
    <!-- Button trigger modal -->
    <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Questionnaire</h4>
              </div>
              <div class="modal-body">
                <%= render 'answers/form', user: current_user, answer: Answer.new, question: @question %>
              </div>
            </div>
          </div>
        </div>
    <% end %>

    <% if (@user == current_user) && (!current_user.answered_minimum_questions? || params[:skip] == "1") %>
      <% content_for(:after_js) do %>
        <script>
          $( document ).ready(function() {
            $('#myModal').modal({
              backdrop: 'static',
              keyboard: false
            });

            // $("#Modalbtn").trigger("click");
            });
        </script>
      <% end %>
    <% end %>

      <% content_for(:after_js) do %>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tour/0.11.0/js/bootstrap-tour.js"></script>
<script>
var tour = new Tour({
  name: 'personnality_tour',
  backdrop: true,
  template: "<div class='popover tour inline'><div class='arrow'></div><h3 class='popover-title text-center text-blue'></h3><div class='popover-content text-center text-blue'></div><div class='popover-navigation text-center'><button class='btn btn-default' data-role='prev'><i class='fa fa-long-arrow-left' aria-hidden='true'></i></button><span data-role='separator'>|</span><button class='btn btn-default' data-role='next'><i class='fa fa-long-arrow-right' aria-hidden='true'></i></button><button class='btn btn-default' data-role='end'>Close</button></div>" ,

  steps: [
  {
    element: "#chartweb1",
    title: "Title",
    content: "This is the main personalities"
  },
  {
    element: "#chartPole",
    title: "title",
    content: "those are the values"
  },
  {
    element: "#insightButton",
    title: "calculate insight",
    content: "Only click after you answered new questions"
  }
]});


// Initialize the tour
tour.init();

// Start the tour

$(document).ready(function(){
  tour.start();
  // tour.restart();
})


</script>

      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.js"></script>

      <script>
    var ctx = $("#chartweb1");
    var data = {
    labels: <%= raw (@user.print_insight.keys[0..30]) %>,
    datasets: [
        {
            label: "Personality",
            backgroundColor: "rgba(71, 61, 138,0.8)",
            borderColor: "#6F58C9",
            pointBackgroundColor: "#6F58C9",
            pointBorderColor: "#fff",
            pointHoverBackgroundColor: "#fff",
            pointHoverBorderColor: "#6F58C9",
          data: <%= raw (@user.print_insight.values[0..30]) %>
        }
    ]
};
new Chart(ctx, {
    type: "radar",
    data: data,
    options: {
            scale: {
                reverse: true,
                ticks: {
                    beginAtZero: true
                }
            }
    }
});
 var ctx = $("#chartPole");
        var data = {
    datasets: [{
        data: <%= raw (@user.print_insight.values[28..36]) %>,
        backgroundColor: [
            "rgba(111, 88, 201, 0.8)",
            "rgba(125, 131, 255, 0.8)",
            "rgba(188, 237, 246, 0.8)",
            "rgba(71, 61, 138, 0.7)",
            "rgba(83,154,237,0.7)",
            "rgba(134, 104, 168, 0.7)",
            "rgba(167,204,237,0.7)"
        ],
        label: 'My dataset' // for legend
    }],
    labels:<%= raw (@user.print_insight.keys[28..36]) %>
};

 new Chart(ctx, {
    data: data,
    type: "polarArea",
    options: {
        elements: {
            arc: {
                borderColor: "#F7F8FB"
            }
        }
    }
});
      </script>
      <%end%>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>