config/routes.rb
Rails.application.routes.draw do

  get 'pusher/auth'

  post 'pusher/auth', to: 'pusher#auth'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :users
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  root to: 'pages#home'

  get 'intro', to: 'pages#intro'

  resources :users, only: [:show, :edit, :update] do
    # delete 'deactivate', on: :member
    member do
      get :personality
      get :questionnaire
      post :calculate_insight
    end

    resources :questions, only: [:show] do
      resources :answers, only: [:new, :create]
    end
  end

  resources :rooms, only: [:create, :show]
  resources :questions, only: [:index, :new, :create, :edit, :update] #pundit
  resources :matches, only: [:index]
  resources :answers, only: [:edit, :update, :destroy]
  resources :ratings, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<div class="tabs">
  <%= link_to(questionnaire_user_path(current_user), options = {class: "tab #{'active' if active == 'questionnaire' }"}) do %>
    <h3><%= image_tag "002-questions.svg", class: "tab-icon"%>Questionnaire</h3>
  <% end %>
  <%= link_to(personality_user_path(current_user.id), options = {class: "tab #{'active' if active == 'personality' }"}) do %>
    <h3><%= image_tag "001-user.svg", class: "tab-icon"%>Personality</h3>
  <% end %>

  <%= link_to(matches_path, options = {class: "tab"}) do %>
    <h3><%= image_tag "003-chat.svg", class: "tab-icon"%>Matches</h3>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<!-- Navbar Collapsing to pages with Node Animation Background -->
<% if current_page?(root_path) || current_page?(intro_path) || devise_controller? %>
  <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">

      <!-- Logo -->
      <div class="navbar-header page-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
          <i class="fa fa-bars"></i>
        </button>
        <%= link_to image_tag("logo.svg"), root_path, class: "navbar-brand" %>
      </div>

      <!-- Different navigation if login or not -->
      <% if user_signed_in? %>

        <!-- Notification -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
        <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link float-left" do %>
          <!-- <div class="badge-container">
            <i class="fa fa-envelope-o"></i>
            <div class="badge badge-blue">3</div> -->
          </div>
        <% end %>

        <!-- Profile picture and dropdown -->
        <div class="navbar-wagon-item float-right">
          <div class="dropdown">
            <%= image_tag "#{current_user.avatar}", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to user_path(current_user) do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to root_path do %>
                  <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% else %>
        <!-- Login text link -->
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
          <ul class="nav navbar-nav"><%# link_to 'event', { controller: :pages, action: :home }, class: 'someClass', id: 'someId'  %>
            <li class="active"><%= link_to 'Home', root_path(anchor: 'intro')%></li>
            <li><%= link_to 'Our Purpose', root_path(anchor: 'about')%></li>
            <li><%= link_to 'How it works', root_path(anchor: 'service')%></li>
            <li><%= link_to 'Contact Us', root_path(anchor: 'contact')%></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Login<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Sign Up", new_user_registration_path, class: "" %></li>
                <li><%= link_to "Login", new_user_session_path, class: "" %></li>
              </ul>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </nav>
<% else %><!-- Navbar Fixed to pages without Node Animation Background -->

  <nav class="navbar-glued" role="navigation">
    <div class="container">

      <!-- Logo -->
      <div class="navbar-header page-scroll">
        <%= link_to image_tag("logo.svg"), root_path, class: "navbar-brand" %>
      </div>

      <!-- Different navigation if login or not -->
      <% if user_signed_in? %>

        <!-- Notification -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
        <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link float-left" do %>
          <!-- <div class="badge-container">
            <i class="fa fa-envelope-o"></i>
            <div class="badge badge-blue">3</div> -->
          </div>
        <% end %>

        <!-- Profile picture and dropdown -->
        <div class="navbar-wagon-item float-right">
          <div class="dropdown">
            <%= image_tag "#{current_user.avatar}", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to user_path(current_user) do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to root_path do %>
                  <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
        <% else %>
        <!-- Login text link -->
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
          <ul class="nav navbar-nav"><%# link_to 'event', { controller: :pages, action: :home }, class: 'someClass', id: 'someId'  %>
            <li class="active"><%= link_to 'Home', root_path(anchor: 'intro')%></li>
            <li><%= link_to 'Our purpose', root_path(anchor: 'about')%></li>
            <li><%= link_to 'How it works', root_path(anchor: 'service')%></li>
            <li><%= link_to 'Contact Us', root_path(anchor: 'contact')%></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Login<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Sign Up", new_user_registration_path, class: "" %></li>
                <li><%= link_to "Login", new_user_session_path, class: "" %></li>
              </ul>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </nav>
<% end %>