config/routes.rb
Rails.application.routes.draw do

  get 'pusher/auth'

  post 'pusher/auth', to: 'pusher#auth'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :users
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  root to: 'pages#home'

  get 'intro', to: 'pages#intro'

  resources :users, only: [:show, :edit, :update] do
    # delete 'deactivate', on: :member
    member do
      get :personality
      get :questionnaire
      post :calculate_insight
    end

    resources :questions, only: [:show] do
      resources :answers, only: [:new, :create]
    end
  end

  resources :rooms, only: [:create, :show]
  resources :questions, only: [:index, :new, :create, :edit, :update] #pundit
  resources :matches, only: [:index]
  resources :answers, only: [:edit, :update, :destroy]
  resources :ratings, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  validates :content, length: { minimum: 1 }

  scope :sum_of_content, -> { all.map(&:content).inject(:+).try(:length).to_i }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  skip_before_action :redirect_to_custom_path, only: :create
  def new
  end

  def create
    @answer = Answer.new(answer_params)
    question = Question.find(params[:question_id])
    @answer.user = current_user


    if @answer.save
      @question = current_user.unanswered_questions

      respond_to do |format|
        format.html { redirect_to user_path(current_user) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'users/show' }
        format.js
      end
    end
  end

  def edit
    @answer = Answer.find(params[:id])
    authorize @answer, :update?
  end

  def update
    @answer = Answer.find(params[:id])
    authorize @answer
    if @answer.update(answer_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    authorize @answer
    @answer.destroy
    redirect_to user_path(current_user)
  end

  private

  def answer_params
    params.require(:answer).permit(:content, :question_id)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
        <%= simple_form_for([user, question, answer], remote: true) do |f| %>

          <h4><%= question.content %></h4>
          <%= f.input :content, label: false, placeholder: "type your answer"%>
          <%= f.input :question_id, as: :hidden, input_html: { value: question.id }  %>
          <div>
            <progress max="100" value= "<%=user.percentage%>"></progress>
          </div>
          <%= link_to "Skip", user_path(user, skip: 1), class: "btn btn-primary" %>
          <%= f.submit "Next", class: "btn btn-primary" %>
          <% if user.answered_minimum_questions? %>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          <% end %>
        <% end %>

app/views/answers/_listing.html.erb
<% user.answers.order("created_at DESC").each do |answer| %>
  <div class="row qa-box">

    <div class="col-xs-1"></div>
    <div class="col-xs-11"> <h1> <%= answer.question.content %></h1></div>

    <div class="col-xs-1 qa-btn">
      <ul>
        <% if policy(answer).edit? %>
          <li><%= link_to (image_tag "001-edit.svg"), edit_answer_path(answer) %></li> <!-- Insert here the links to edit -->
        <% end %>
        <% if policy(answer).destroy? %>
          <li><%= link_to (image_tag "002-trash.svg"), answer_path(answer), method: :delete, data: {confirm: "Are you sure?"}%></li>
         <% end %> <!-- Insert here the links to delete -->
      </ul>
    </div>
    <div class="col-xs-11"> <!-- Insert here the answer -->
      <p> <%= answer.content %> </p>
    </div>
  </div>
  <div class="row qa-link">
    <div class="col-xs-9"></div>
    <div class="col-xs-3">
      <% if user == current_user %>
        <%= link_to "Click here to answer more questions", "#myModal", id: "Modalbtn", data: {toggle:"modal", target:"#myModal"}  %>
      <%end%>
    </div>
  </div>
<%end%>

app/views/answers/create.html.erb
<h1>Answers#create</h1>
<p>Find me in app/views/answers/create.html.erb</p>

app/views/answers/create.js.erb
<% if @answer.errors.any? %>
  // Render new answer form with errors
  $('#new_answer').html("<%= j render 'answers/form', user: current_user, question: @question, answer: @answer %>");
<% else %>
  // Reset the form
  $('#new_answer').html("<%= j render 'answers/form', user: current_user, question: @question, answer: Answer.new %>");
  // Reloads the page
  $('#questionnaire').html("<%= j render 'answers/listing', user: current_user %>");
<% end %>

app/views/answers/edit.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<%= simple_form_for @answer do |f| %>
  <%= f.input :content %>
  <%= f.submit "UPDATE ANSWER", class: "btn btn-primary" %>
<%end%>

app/views/answers/new.html.erb
<!-- Button trigger modal -->
<!-- <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Discover Yourself!
</button> -->


<!-- Modal -->
<!-- <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <%#= simple_form_for [@user, @question, @answer] do |f| %>
        <%#= f.input :content, placeholder: "Look within, take your time, you will find the answer!" %>
        <%#= f.submit "Done", type: "hidden" %>
        <%#end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Skip >> </button>
        <button type="button" class="btn btn-primary">Next >> </button>
      </div>
    </div>
  </div>
</div> -->

app/views/answers/update.html.erb
<h1>Answers#update</h1>
<p>Find me in app/views/answers/update.html.erb</p>